server:
  port: 8001
  servlet:
    context-path: /index

spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
      initial-size: 10
      max-active: 50
      min-idle: 5
      max-wait: 60000
#  servlet:
#    multipart:
#      max-file-size: 10485760
#      max-request-size: 104857600


mybatis:
  type-aliases-package: com.etc.blogTest.entity
  mapper-locations: classpath:resources.mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true


#file:
#  upload-path: /upload/**
#  static-access-path: E:/upload/


